function [model] = simulate_model(model, params)
    for i = 1:params.n - 1
        if rem(i, 500) == 0 % timer of the simulation
            % disp([i, params.n]);
            percentage = (i / (params.n - 1)) * 100;
            disp(['Step: ', num2str(i), '/', num2str(params.n), ...
            ' (', num2str(percentage, '%.1f'), '% complete)']);
        end
        % if i == floor(params.n/2)
        %     sendTelegramMessage('50% complete...');
        % end
        
        model = step_neurons(model, params, i);

        if params.stimulation_mode && params.stimulation_neuro_E % Automatic stimulation (enhance, disrupt)
            [model.neuron_astrozone_activity_Glu(:, :, i), model.I_app_astro] = ... % I_stim is added to I_app_astro
            get_neuron_astrozone_activity(model.G(:, i + 1), ...
                                          model.T_Iapp_met(i),...
                                          model.Iapp,...
                                          model.auto_electrode_neuro_E_stim_timed(:, i + 1)); 

        elseif ~params.stimulation_mode && params.stimulation_neuro_E % Manual stimulation (augmentation)
            [model.neuron_astrozone_activity_Glu(:, :, i), model.I_app_astro] = ...
            get_neuron_astrozone_activity(model.G(:, i + 1), ...
                                          model.T_Iapp_met(i),...
                                          model.Iapp,...
                                          model.manual_electrode_neuro_E_stim_timed(:, i + 1)); 

        else % No stimulation
            [model.neuron_astrozone_activity_Glu(:, :, i), model.I_app_astro] = ...
                get_neuron_astrozone_activity(model.G(:, i + 1), ...
                                              model.T_Iapp_met(i),...
                                              model.Iapp,...
                                              0); 
        end
        [model.Ca(:, :, i + 1), ...
            model.H(:, :, 1), ...
            model.IP3(:, :, i + 1), ...
            model.W_WM, ...
            model.Ineuro, ...
            model.Gli_global(:, :, i + 1), ...
            model.neuron_astrozone_input_timings] = ...
            step_astrocytes(model.neuron_astrozone_activity_Glu(:, :, i), ...
                            model.Ineuro, i, ...
                            model.Ca(:, :, i), ...
                            model.H(:, :, 1), ...
                            model.IP3(:, :, i), ...
                            model.W_WM, ...
                            model.Gli_global(:, :, i), ...
                            model.neuron_astrozone_input_timings,...
                            model.I_app_astro);
                            
        
        [model.Ca_expand(:, :, i + 1), ...
            model.Gli_global_expand] = ...
            expand_astrocytes(model.Ca(:, :, i + 1), ...
                              model.Gli_global(:, :, i + 1));
        % Enhance
        if params.stimulation_mode && ...
           params.stimulation_neuro_E &&...
           i == params.stim_start_neuro_E - 1

            [model.auto_electrode_neuro_E_stim_timed] = ...
                stimulator_enhance(params, model, i);
        end

        % Disruption
        if params.stimulation_mode && params.stimulation_neuro_I
            [model.auto_electrode_neuro_I_stim_timed, ...
                model.electrode_neuron_total_rec, ...
                model.integral_electrode_rec_dist, ...
                model.integral_electrode_rec3] = ...
                stimulator_dist(params, model, i,...
                                model.electrode_neuron_total_rec,...
                                model.auto_electrode_neuro_I_stim_timed,...
                                model.integral_electrode_rec_dist, ...
                                model.integral_electrode_rec3);
        end
        % Augmentation
        % There is no dedicated function for this mode.
        % In this mode, the selected electrodes in "init_model.m" are applied to 
        % "get_neuron_astrozone_activity" in the manual mode.

    end
    
end